# This docker-compose is provided for developer convenience only
# the authoritative service-setup required for the integration tests
# will always be in the CI workflows (.github/workflows/*)
version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: pASSw0rd
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433